services:
  web:
    container_name: rsserpent
    image: ghcr.io/ekkog/rsserpent:master
    ports:
      - "8000:8000"
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/app/cache
    volumes:
      - ./.cache:/app/cache
      - ./plugins:/app/plugins
      - ./rsserpent.txt:/app/rsserpent.txt